### ISSUE TITLE
The number of negative items is changed

### ISSUE THREAD

**Issue by MinSeok-Pons-Kim** [THUwangcy/ReChorus#10]
Hi again 👍 

I was writing down some codes and I found that the default parameter 'neg_items' in BaseModel.py is changed from 99 to 1, while amazon.ipynb has still the original 99. Any reason for that? The paper says it's 99, so a bit confusing.

**Comment by THUwangcy** [comment]
A little misunderstanding. The 'num_neg' parameter in BaseModel.py means the number of negative items sampled for training (default 1 for the pair-wise loss). While it also supports sampling multiple negative items to calculate the loss, which can be determined by this parameter.

**Comment by MinSeok-Pons-Kim** [comment]
Please correct me if I'm wrong. This parameter controls the number of negative items which can be used as 1 or 99 or any other arbitrary number, while the "originally intended" parameter value is 99, to fit the experimental setting of the paper [Make it a Chorus ...,]. Am I correct?

**Comment by THUwangcy** [comment]
First, let's make it clear that there are two kinds of negative items with different usages: 1) testing negative items, which will be ranked together with the ground-truth item, and 2) training negative items, which are used to calculate the pair-wise ranking loss.

The former is the one you mentioned. This number (say 99) is automatically determined by the provided data (according to the 'neg_items' column). The latter is set by the 'num_neg' parameter, which should be 1 according to the paper Eq. (5).

**Comment by MinSeok-Pons-Kim** [comment]
Thanks for clearing. So the loss of one positive item should be made with 1 negative item during training, and the recommendation would be to sort 1 positive and 99 negative items.
Although the default BPR loss in the code seems to be "compatible with" multiple negative items, it's 1 negative item "in your setting". Is it right?

**Comment by THUwangcy** [comment]
Yes, exactly:)

**Comment by MinSeok-Pons-Kim** [comment]
It helped a lot! Thanks very much again 👍
