### ISSUE TITLE
GRU4Rec on users without any previous history

### ISSUE THREAD

**Issue by MinSeok-Pons-Kim** [THUwangcy/ReChorus#13]
Hi, I want to ask whether GRU4Rec can recommend items to users without previous history. At least to me the code seems so.

**Comment by MinSeok-Pons-Kim** [comment]
If there are k users without history and n users with history, the current version seems to evaluate result only on n users, which is (result of n users) / n

If k users are to be included in the evaluation, would it be okay to just (result of n users + 0) / (n+k) supposing that the recommendation results for k users are all zero?

**Comment by THUwangcy** [comment]
In fact, GRU4Rec cannot recommend items without history. But the current implementation will simply drop the instances with no historical interaction, referring to BaseModel.py → SequentialModel → _prepare(). Generally, all the users in the evaluation should be ensured to have at least one historical interaction for sequential models (leave-one-out strategy assures this). 

As for the stated solution, I'm also not sure whether it is acceptable. Maybe a little unfair when compared to general recommendation models.

**Comment by MinSeok-Pons-Kim** [comment]
I agree with your idea. Thanks for explanation.
