### ISSUE TITLE
CFKG模型

### ISSUE THREAD

**Issue by hzau96yhz** [THUwangcy/ReChorus#14]
想问一下CFKG这个模型，构建的KG数据集是在哪个文件里，也是在data目录里吗

**Comment by hzau96yhz** [comment]
文档里说得item_meta.csv（可选）
其格式： item_id \t i_<attribute> \t ... \t r_<relation> \t ...
可选，仅某些型号（CFKG，SLRC +，Chorus，KDA）需要。

但里边是这样的 item_id	  i_category	r_complement   r_substitute
您能说明一下后边这两个r_complement   r_substitute表示什么含义吗？

**Comment by THUwangcy** [comment]
表示商品之间的关系，和当前 item_id 有关系的商品以列表形式存在对应列中。比如 item_id 为 1，r_complememt 为 [2,3]，表示对于互补这个关系来说，1 的互补品有 2 和 3，(1, complement, 2) 和 (1, complement, 3) 两个三元组在 KG 中。因为这个里面都是商品之间的关系，就用这种方式存储了。构建 KG 的过程可以参考 KGReader 的实现。
