### ISSUE TITLE
Chorus input error

### ISSUE THREAD

**Issue by tks1998** [THUwangcy/ReChorus#15]
raise ValueError('The value argument must be within the support')
ValueError: The value argument must be within the support

My input 
![error](https://user-images.githubusercontent.com/37293650/110605156-6814e780-81bb-11eb-9515-b4e82a3ef91e.png)

code's log
![codelog](https://user-images.githubusercontent.com/37293650/110605283-8da1f100-81bb-11eb-80c3-49438fa14796.PNG)

Please help me.

**Comment by THUwangcy** [comment]
A little hard to figure out the problem from this error message. But it seems that the time column is strange. It should be UNIX timestamps (int) in ascending order. Make sure the time column takes correct values and if the problem still exists, maybe you can output `beta` and `delta_t` to see in which case `exp_dist` will lead to this problem (reproduce the error with a small snippet).

P.S. Has the `user_id` been re-indexed from 1? The user number seems quite large with indexes over 315k.

**Comment by tks1998** [comment]
Yes, I reindex from 1. But I split train valid test and some user_id has only one transaction so dev set not include the same user with train set.

**Comment by tks1998** [comment]
@THUwangcy my output that is [[-0. , -0., -0.]] ... Please help me

**Comment by THUwangcy** [comment]
Still hard to figure out the problem with such limited information. It will be better to manually construct some inputs and provide a small snippet that can reproduce the error.

**Comment by tks1998** [comment]
Of course, This is a training dataset. Thank for  your support @THUwangcy 

[dataset.zip](https://github.com/THUwangcy/ReChorus/files/6147750/dataset.zip)
Thank you for your support

**Comment by tks1998** [comment]
@THUwangcy  can you help me :( ?

**Comment by THUwangcy** [comment]
I tried but I can't reproduce the error with the dataset provided.
