### ISSUE TITLE
How to convert predict to real item ?

### ISSUE THREAD

**Issue by tks1998** [THUwangcy/ReChorus#16]
Following the document, Currently I run TiSAS model the output include [[score grouth truth, k-score-item],[....],[....]] and I don't know how to convert score to item? Please help me! Thank for your support.

**Comment by THUwangcy** [comment]
The scores correspond to the [item_id, neg_items] in test.csv / dev.csv. Maybe you can refer to the last reply of this issue #5.

**Comment by tks1998** [comment]
thank you

**Comment by THUwangcy** [comment]
Just also need to export the recommended item list for each user in the test set. Leave the codes here for reference.
```
dataset = data_dict['dev']
predictions = runner.predict(dataset)  # n_users, n_candidates
users, rec_items = list(), list()
for i in range(len(dataset)):
    info = dataset[i]
    users.append(info['user_id'])
    item_scores = zip(info['item_id'], predictions[i])
    sorted_lst = sorted(item_scores, key=lambda x: x[1], reverse=True)[:100]  # top-100
    rec_items.append([x[0] for x in sorted_lst])
rec_df = pd.DataFrame(columns=['user_id', 'rec_items'])
rec_df['user_id'] = users
rec_df['rec_items'] = rec_items
```
