### ISSUE TITLE
GRU4Rec Runtime error for pytorch v1.8

### ISSUE THREAD

**Issue by TalonCB** [THUwangcy/ReChorus#18]
**Issue**: GRU4Rec model run will encounter runtime error "RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor"

**Error code location**: ReChorus/src/models/sequential/GRU4Rec.py line 52

**Reason**: in latest pytorch version (maybe after pytorch v1.4), nn.utils.rnn.pack_padded_sequence requires lengths tensor to be CPU int 64 tensor instead of GPU long tensor. 

**Fix Solution**: add .cpu() to sort_his_lengths. e.g. 
        history_packed = torch.nn.utils.rnn.pack_padded_sequence(sort_his_vectors, sort_his_lengths.cpu(), batch_first=True)

**Comment by THUwangcy** [comment]
Thanks again! We have also fixed this to refine codes.
