### ISSUE TITLE
Reference for CFKG

### ISSUE THREAD

**Issue by QingyaoAi** [THUwangcy/ReChorus#2]
FYI, the current reference to CFKG is linked to the short paper. A more comprehensive description of CFKG can be found in the journal paper "Learning heterogeneous knowledge base embeddings for explainable recommendation" (https://www.mdpi.com/1999-4893/11/9/137/pdf). It might worth linking to that as well :)

**Comment by THUwangcy** [comment]
Thanks for the information! Updated now :)
