### ISSUE TITLE
About the baseline "RCF".

### ISSUE THREAD

**Issue by paulpig** [THUwangcy/ReChorus#22]
Hello, I am very interested in your work. 

I find that "RCF" is used for your baseline, and I want to know what item relations are used in your implementation of RCF on Amazon datasets.  If it is convenient for you, can you send me the code of "RCF" that you implemented?  Look forward to your reply.

**Comment by THUwangcy** [comment]
Hi, thanks for your interest. The item relations used in RCF are the same as those in KDA (i.e., also_buy, also_view, buy_together, brand, price, category). We directly modified the original code of RCF, but we did not retain the codes (a little messy). You can refer to this [repository](https://github.com/xinxin-me/RCF).
