### ISSUE TITLE
About the model KDA

### ISSUE THREAD

**Issue by zzj0123** [THUwangcy/ReChorus#23]
In the model KDA, according to your experimental parameter setting method, I found that the experimental results in your table in github can only be reached for the time being HR@5: 0.5174, NDGG@5: 0.3876, but the result in the paper is 0.4201 and in run.sh The experimental result of more fine-grained parameter setting is not up to 0.47 temporarily. Could you please give me some guidance? Looking forward to your reply

**Comment by THUwangcy** [comment]
The results in the table of github are evaluated on the Amazon Grocery dataset, while the paper uses the Amazon Electronics dataset. You can checkout to the TOIS21 branch, and the cmd to reproduce the results in paper is included in run.sh.
