### ISSUE TITLE
About the baseline TiSASRec

### ISSUE THREAD

**Issue by chenliang-zhang** [THUwangcy/ReChorus#24]
When computing the user_min_interval, you use the interval_matrix = np.abs(time_seqs[:, None] - time_seqs[None, :]). As  the diagnal line of the matrix is  always  all-zero, min_interval = np.min(interval + (interval <= 0) * 0xFFFF) will be 0xFFFF for all users. By the way, I  correct the computation of  user_min_interval, but the performance of TiSASRec doesn't get any improvement. This seems to be not important.

**Comment by THUwangcy** [comment]
I'm afraid I do not get the point. The diagonal elements are expected to be all-zero. To avoid np.min yields zero or negative values, we add a large number (0xFFFF) to these positions so that the min operation gets the minimal positive value in the original `interval_matrix`.
