### ISSUE TITLE
About The Model ComiRec

### ISSUE THREAD

**Issue by HeyWeCome** [THUwangcy/ReChorus#25]
Hi, I was looking for a pytorch implementation of this [paper](https://arxiv.org/abs/2005.09347) recently. After flipping through GitHub, I found that there is a file called ComiRec in your project. I'm not sure whether it is the complete implement of that paper. Looking forward to your reply. :)

**Comment by THUwangcy** [comment]
Yes, it is an implementation of ComiRec-SA (self-attention based multi-interest extraction) with the diversity tradeoff parameter `lambda = 0`.

**Comment by HeyWeCome** [comment]
Thanks, very nice code.
