### ISSUE TITLE
about the dataset rechorus

### ISSUE THREAD

**Issue by zzj0123** [THUwangcy/ReChorus#26]
Hello, can you tell me how the "relational ratio in test set" in the paper Rechorus is calculated? thank you very much

**Comment by THUwangcy** [comment]
Assuming we have 10 interactions in the test set, together with 10 corresponding historical sequences, we examine whether each testing item i_t is relational to any item j in the historical sequence (e.g., <j, also_buy, i_t> holds). If 3 testing items can be found relational to at least one item in the historical sequence, the relational ratio in test set is 30%.

**Comment by zzj0123** [comment]
thank you!!!
