### ISSUE TITLE
About the model "GRU4Rec"

### ISSUE THREAD

**Issue by HeyWeCome** [THUwangcy/ReChorus#27]
Hi Wang,
  Today I run "GRU4Rec" with command `python main.py --model_name GRU4Rec --emb_size 64 --hidden_size 128 --lr 1e-3 --l2 1e-4 --history_max 20` as shown in the code.
  However, the results of the run are far from the results mentioned in your paper, Can you give me some guidance?
  My result:
  `(HR@5:0.3203,NDCG@5:0.2223,HR@10:0.4232,NDCG@10:0.2555,HR@20:0.5417,NDCG@20:0.2854,HR@50:0.7626,NDCG@50:0.3289)`
  In your paper:
  `(HR@5:0.3704,NDCG@5:0.2643,HR@10:0.4721,NDCG@10:0.2972,`

  looking forward to your reply.

**Comment by THUwangcy** [comment]
You can try to change line 63: `pred_vectors = self.pred_embeddings(i_ids)` to `pred_vectors = self.i_embeddings(i_ids)`, which is commented in line 64. Actually, this is a difference we found between common practice (line 64) about GRU4Rec and its original paper (line 63). We used the common practice when writing the paper but changed to line 63 afterward to be consistent with the original paper.

**Comment by HeyWeCome** [comment]
Thanks, it works.
