### ISSUE TITLE
Fix bug in NARM

### ISSUE THREAD

**Issue by HeyWeCome** [THUwangcy/ReChorus#28]
Issue: ![A2J3(34R 6U7LK_77P1F3(8](https://user-images.githubusercontent.com/30435835/144231130-6292604a-9972-4ae5-80cf-dd147350325b.png)

location: ReChorus/src/models/sequential/NARM.py line 61

Reason: #18 

Fix Solution: add .cpu() to sort_his_lengths.
history_packed = torch.nn.utils.rnn.pack_padded_sequence(sort_his_vectors, sort_his_lengths.cpu(), batch_first=True)

**Comment by THUwangcy** [comment]
Thanks for pointing it out. Fixed it.
