### ISSUE TITLE
 Framework for hyperparameter Tuning

### ISSUE THREAD

**Issue by Koneru1919** [THUwangcy/ReChorus#34]
Hi,

Firstly, the package looks great and informative. Thanks.

I was just working on the models and was interested in optimzing the hyperparameters of the models . I neverthless tried to understand , but was finding it challenging if package such as Optuna can be used for optimizing the hyperparameters.

Any help or comments on this topic would be helpful !

Thanks in advance!

**Comment by THUwangcy** [comment]
Thanks for your usage of this package. I'm not quite familiar with Optuna, so I'm not sure whether ReChorus can work with it. However, as for hyperparameter tuning, I have a developing python script to multi-thread search hyperparameters under this framework. I can send you the script via email to see if it would help :)

**Comment by Koneru1919** [comment]
Thank you for your reply.

It would be interesting to work on the script further. It would be helpful , if you can send the script to my -Email harshith202@gmail.com).

Thank you :)
