### ISSUE TITLE
关于CMCC数据集

### ISSUE THREAD

**Issue by DuTim** [THUwangcy/ReChorus#37]
您好:
       关于在CIKM2022(TiMiRec)中使用的CMCC数据集是否可以提供? 😃 
       感谢 👍

**Comment by THUwangcy** [comment]
这个是公司内部的私有数据集，审批流程比较严格，目前还无法提供，可以在另外两个公开数据集上测试~

**Comment by DuTim** [comment]
好的,感谢您的回复.
