### ISSUE TITLE
ContraRec训练报错

### ISSUE THREAD

**Issue by Donowert** [THUwangcy/ReChorus#38]
作者您好，我用pytorch1.8版本测试ContraRec的训练发生了下图的错误。
![image](https://user-images.githubusercontent.com/118146653/201562880-d949cf00-8569-46a1-b222-c5651b6b33b7.png)
请问是因为torch不是1.1版本导致的吗？

**Comment by THUwangcy** [comment]
应该是的，可能需要把 torch.arange(batch_size) 规定为 torch.long 类型，默认应该是 float

**Comment by Donowert** [comment]
谢谢大佬，我试试。

**Comment by Donowert** [comment]
我加了一个long类型，还是报错
![image](https://user-images.githubusercontent.com/118146653/201591180-62c933e8-d879-4633-95cb-96d1c2250c70.png)

**Comment by THUwangcy** [comment]
lengths 也加一个 .long() 试试

**Comment by Donowert** [comment]
![image](https://user-images.githubusercontent.com/118146653/201594290-a1295184-00e3-4c49-be11-cb85c589140a.png)

加了以后能跑起来，但是loss一致不变
![image](https://user-images.githubusercontent.com/118146653/201594335-763bd87a-3bfd-414c-bf1b-3718f887c26e.png)

**Comment by Donowert** [comment]
![image](https://user-images.githubusercontent.com/118146653/201594837-4bc7d50d-7ba0-4384-982d-3114e9634aa9.png)
 这是跑完后的结果

**Comment by THUwangcy** [comment]
感觉是 torch 版本还带来了其它问题，在 1.1 下刚刚测试还是正常的，之后我再细查一下

**Comment by Donowert** [comment]
Caser我试了下好像没问题，麻烦大佬了！

**Comment by Donowert** [comment]
![image](https://user-images.githubusercontent.com/118146653/201596479-87b41152-2303-4b18-8a6e-3ccfe7db56cf.png)
Caser好像也有问题，应该是版本的问题
