### ISSUE TITLE
How to get top K recommendations for any interaction?

### ISSUE THREAD

**Issue by maneelusf** [THUwangcy/ReChorus#42]
Hello,

Thanks for implementing this beautiful library. I have a couple of queries:-

1. Is there any code on generating the top 10 recommendations given a user input particular set of interactions?
3. When we generate results on the test dataset, aren't we supposed to calculate the scores for every item present in the dataset instead of just the ground truth and the negative sampled items? I believe the code is just for the negative sampled items as well as the ground truth(a total of 100) when in reality it should have been done for all of the items(3707 in the case of ML 1m)?

**Comment by THUwangcy** [comment]
1. The current function [save_rec_results](https://github.com/THUwangcy/ReChorus/blob/1dea25bf955fc37ac997d728cc959d9916b50ff4/src/main.py#L85) in `main.py` can save top-k recommended items. The issue [#5](https://github.com/THUwangcy/ReChorus/issues/5#issue-665318427) also has more information.
2. The default evaluation strategy is based on sampling. We also support non-sampling evaluation controlled by the hyper-parameter `test_all`. But we do not optimize the efficiency for this setting.
