### ISSUE TITLE
An issue on implementation of ComiRec

### ISSUE THREAD

**Issue by Ethan00Si** [THUwangcy/ReChorus#46]
<img width="895" alt="image" src="https://github.com/THUwangcy/ReChorus/assets/48440583/b2a81d73-b69c-475b-a653-7dd0424c4f00">

It seems that 'his_vectors' in this [line](https://github.com/THUwangcy/ReChorus/blob/fb646d4eed13a8d81ae308965b08c816f40d1a57/src/models/sequential/ComiRec.py#L80C29-L80C40) should be 'his_pos_vectors'.
When 'self.add_pos' is set to True,  we should use 'his_pos_vectors' instead of 'his_vectors'.
In my experiments, alter 'his_vectors' into 'his_pos_vectors' can lead to significant performance improvement when setting 'self.add_pos' to True.

**Comment by THUwangcy** [comment]
Sorry for the late rely. We also think it is more effective to aggregate 'his_pos_vectors', but we chose to follow the [official code of ComiRec](https://github.com/THUDM/ComiRec/blob/master/src/model.py):
![截屏2023-08-27 17 21 27](https://github.com/THUwangcy/ReChorus/assets/17726134/b321073c-d55a-47d8-836b-06eb2b52532b)

**Comment by Ethan00Si** [comment]
Thanks for your response. It fully addresses my concern.
