### ISSUE TITLE
About the experimental result on the CLRec model

### ISSUE THREAD

**Issue by junyi006** [THUwangcy/ReChorus#48]
Hello, I am very interested in your paper 《Contrastive Learning for Sequential Recommendation》. However, I have some questions when reproducing the experiments. The baseline model I reproduced is consistent with the results in your readme table, but the experimental results of the CLRec model are not ideal. The value of the HR@5 metric is only 0.4808. Could you provide the parameters of this model? Or could you point out any possible operational errors on my part?

**Comment by junyi006** [comment]
Hello, I couldn't find the code for your data augmentation section, nor could I find the code for data augmentation. Can you help me point it out

**Comment by HeyWeCome** [comment]
Maybe I can answer that question for you. There is a Dataset class included in every model. The data enhancement method can be found here. For example, lines 106 to 138 of ContraRec performs reorder and mask to data augmentation in the train phase, respectively.

> Hello, I couldn't find the code for your data augmentation section, nor could I find the code for data augmentation. Can you help me point it out

**Comment by junyi006** [comment]
> 也许我可以为你回答这个问题。每个模型中都包含一个 Dataset 类。数据增强方法可以在这里找到。例如，ContraRec 的第 106 行到第 138 行分别在训练阶段执行重新排序和掩码到数据增强。
> 
> > 您好，我找不到您的数据增强部分的代码，也找不到数据增强的代码。你能帮我指出来吗

I am very sorry for my carelessness and thank you very much for your answer. I mistook the CLRec model for CL4SRec, which led to this joke. Thank you again for your answer
