### ISSUE TITLE
How do we leverage the predict endpoints

### ISSUE THREAD

**Issue by Akhilj786** [THUwangcy/ReChorus#5]
I was able to train on one of the cellphone dataset.
![image](https://user-images.githubusercontent.com/3736087/88419250-b941a980-cd99-11ea-874d-86e99020182f.png)
![image](https://user-images.githubusercontent.com/3736087/88419374-eee69280-cd99-11ea-8328-38af8e78c93f.png)
But how do we call the inference or predict endpoints? I believe there is Baserunner class but that expects args right?

Is there some sample code to do that?

**Comment by THUwangcy** [comment]
If you want to get prediction scores for the test set, you can use the `predict` function in `BaseRunner`, which will return the ranking scores for a given model and data.

For example, you can add the following codes after `runner.train(model, data_dict)` in `main.py` (outside the if scope):
```
predictions = runner.predict(model, data_dict['test'])
print('\n', predictions.shape, '\n', predictions)
```
And then run cmds with `--train 0 --load 1`. You will get outputs with shape (num_test_data, num_candidates), and the first column is the score for the ground-truth item. You can then save them for further usage. Hope it helps.

> PS: In case you want to reproduce the results of Chorus, you should also run the model with `--stage 2`. The model saved should start with 'Chorus' but not 'KG'.

**Comment by Akhilj786** [comment]
@THUwangcy Yeah that's right i was able to get that working.
```
    num_array = runner.predict(model, data_dict['test'])
    logging.info(
        "Predict Endpoint type:{0} size:{1} shape:{2}".format(type(num_array), num_array.ndim, num_array.shape))
    logging.info(data_dict['test'])
    item_dict=dict(zip(data_dict['test']._get_feed_dict(1)['item_id'], num_array[1]))
    sorted_dict = dict(sorted(item_dict.items(), key=operator.itemgetter(1),reverse=True)[:5])
    print(sorted_dict)

```
