### ISSUE TITLE
About code of `DIEN` model for user beheaviers modelling

### ISSUE THREAD

**Issue by Zeng-B-B** [THUwangcy/ReChorus#56]
In the code at line 122 of `src/models/context_seq/DIEN.py`, there is the following expression:
```python
attention_score=(attention_prod−attention_prod.max()).softmax(dim=−2)
```
Why is there a subtraction of `attention_prod.max()`? According to the original DIEN paper, it seems that simply using softmax for row normalization should suffice.

Could someone please explain this? Thank you.
![image](https://github.com/user-attachments/assets/f0ea0ca3-41af-49d2-bd4d-7f11598dc6a3)

**Comment by JiayuLi-997** [comment]
This is due to computational considerations: directly applying the exp operation on large scores can easily cause overflow. Such an operation ensures that there are no issues in the computation process while keeping the results unchanged.
