### ISSUE TITLE
TiSASRec模型求时间间隔有误

### ISSUE THREAD

**Issue by DgtlCdy** [THUwangcy/ReChorus#57]
此处代码：
`min_interval = np.min(interval_matrix + (interval_matrix <= 0) * 0xFFFF)`
0xFFFF只有16位，在一些数据集的time参数中是非常小的数，导致最后算出来的时间间隔都是这个数，最后模型效果会不好。
可改为0xFFFFFFFF。

**Comment by JiayuLi-997** [comment]
感谢你的建议！虽然通常情况下，我们定义time为实际timestamp，不会出现该问题，但为了避免该情况在特殊数据集中出现，我们按照你的建议进行了修改。谢谢！
